### PR TITLE
chore(dsl)!: Remove `compute_merkle_root` opcode

### LINKED ISSUE #461: Remove `ComputeMerkleRootConstraint` from `dsl`
ACIR not longer contains this black box function so we don't need to support this constraint type in Barretenberg.

https://github.com/noir-lang/acvm/pull/296

### PR DESCRIPTION
**Pull request by kevaundray**
# Description

Closes #461 

# Checklist:

- [ ] I have reviewed my diff in github, line by line.
- [ ] Every change is related to the PR description.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this pull request to the issue(s) that it resolves.
- [ ] There are no unexpected formatting changes, superfluous debug logs, or commented-out code.
- [ ] There are no circuit changes, OR specifications in `/markdown/specs` have been updated.
- [ ] There are no circuit changes, OR a cryptographer has been assigned for review.
- [ ] I've updated any terraform that needs updating (e.g. environment variables) for deployment.
- [ ] The branch has been rebased against the head of its merge target.
- [ ] I'm happy for the PR to be merged at the reviewer's next convenience.
- [ ] New functions, classes, etc. have been documented according to the doxygen comment format. Classes and structs must have `@brief` describing the intended functionality.
- [ ] If existing code has been modified, such documentation has been added or updated.

### CODE REVIEW

**Comment by TomAFrench** [comment]
Looks good but we should hold off on merging until we have a branch of `acvm-backend-barretenberg` which passes.

**Comment by TomAFrench** [comment]
https://github.com/noir-lang/acvm-backend-barretenberg/pull/210 PR is up here. I'm getting test failures on this.

**Comment by kevaundray** [comment]
> [noir-lang/acvm-backend-barretenberg#210](https://github.com/noir-lang/acvm-backend-barretenberg/pull/210) PR is up here. I'm getting test failures on this.

Currently blocked in Noir as something has changed with pedersen since the last commit

**Comment by kevaundray** [comment]
We are using #499 which cherry-pick's this PR and is working in ccvm-backend-barretenberg and Noir

**Pull request merged**
