### PR TITLE
chore(ci): Add Noir CI that runs with a github label

### LINKED ISSUE #431: Add Noir tests to CI
Barretenberg should have a way to run the Noir test suite against a PR to check if something would break Noir.

### PR DESCRIPTION
**Pull request by phated**
# Description

This adds a workflow for building and running all tests of Noir against a specific PR. Since it builds Barretenberg from scratch it takes >50 minutes to run. With that in mind, I've made it so the workflow only runs if you add the "noir-ci" label to a PR (as I've done on this PR to demonstrate).

This also uses the Nix build process that the Noir team uses so running this CI also ensures that nothing was broken with usage of the Nix package manager.

Closes #431

# Checklist:

- [x] I have reviewed my diff in github, line by line.
- [x] Every change is related to the PR description.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this pull request to the issue(s) that it resolves.
- [x] There are no unexpected formatting changes, superfluous debug logs, or commented-out code.
- [x] There are no circuit changes, OR specifications in `/markdown/specs` have been updated.
- [x] There are no circuit changes, OR a cryptographer has been assigned for review.
- [x] I've updated any terraform that needs updating (e.g. environment variables) for deployment.
- [x] The branch has been rebased against the head of its merge target.
- [x] I'm happy for the PR to be merged at the reviewer's next convenience.
- [x] New functions, classes, etc. have been documented according to the doxygen comment format. Classes and structs must have `@brief` describing the intended functionality.
- [x] If existing code has been modified, such documentation has been added or updated.

### CODE REVIEW

**Comment by dbanks12** [comment]
Very clean.... Lgtm. I'll keep an eye on it and review+approve when you're all done 🙂

**Comment by dbanks12** [comment]
Is this the stupid solidity verifier bug again causing CI fail randomly 🙄

**Comment by phated** [comment]
@dbanks12 I think there's a solidity CI bug (again?) and also upstream master of BB has broken Noir so the Noir tests are failing. I've not spent any time to find out what commit caused it.

**Comment by dbanks12** [comment]
@ludamad is the verifier failure the same one we've been seeing elsewhere?

**Comment by dbanks12** [comment]
Sorry pinged wrong person.... Meant to ping @cheethas

**Comment by Maddiaa0** [comment]
> Sorry pinged wrong person.... Meant to ping @cheethas

I'll try get this sorted first thing tomorrow

**Review by kobyhallx — APPROVED** [review]
This looks good 👍

**Pull request merged**
